language: python
python:
    - "2.7"
before_install:
    - pip install pytest pytest-cov
before_script:
    - psql -c 'create database sensei_test;' -U postgres
script:
    - py.test
sudo: required
dist: precise
addons:
    postgresql: "9.5"
services:
    - postgresql
