"""empty message

Revision ID: fccffb2e4db6
Revises: 0745219a2583
Create Date: 2018-03-05 15:32:55.741303

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fccffb2e4db6'
down_revision = '0745219a2583'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('area', sa.Column('x_position', sa.Float(), nullable=True))
    op.add_column('area', sa.Column('y_position', sa.Float(), nullable=True))
    op.add_column('area', sa.Column('z_position', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('area', 'z_position')
    op.drop_column('area', 'y_position')
    op.drop_column('area', 'x_position')
    # ### end Alembic commands ###
