# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: Sensei API
  description: Augmenting Classroom Observation
  version: "1.0.0"
# the domain of the service
host: sensei-server.herokuapp.com
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /api/v1
produces:
  - application/json
securityDefinitions:
  basicAuth:
    type: basic
    description: HTTP Basic Authentication. Requires `HTTPS`
paths:
  /proximity_events:
    post:
      summary: Proximity Events
      description: |
        The Proximity Events endpoint provides a way to upload proximity observations from sensors to the sensei platform.
      consumes:
        - application/json
      parameters:
        - name: events
          in: body
          description: List of proximity events.
          required: true
          schema:
            type: array
            items:
              $ref: '#/definitions/ProximityEvent'
      tags:
        - Sensors
      security:
        - basicAuth: []
      responses:
        200:
          description: Upload accepted
        401:
          description: Unauthorized
definitions:
  ProximityEvent:
    type: object
    description: Proximity events occur when when sensor receives a radio packet from another sensor. The receiver records the observed RSSI of the packet, along with the sender's id and a timestamp. 
    properties:
      classroom_id:
        type: integer
        description: Unique identifier for the classroom that the sensors involved belong to.
      local_id:
        type: integer
        description: Classroom specific sensor id of the sensor that recorded the proximity event (0-255).
      remote_id:
        type: integer
        description: The id of the sensor that sent the triggering packet (0-255).
      observed_at:
        type: string
        description: The timestamp of the event, in iso8601 format. Example '2002-12-25T12:15:05'
      rssi:
        type: number
        description: The signal strength, represented as a negative number of decibels.
